# Generated by Django 4.2.2 on 2023-06-21 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="author",
            new_name="_author",
        ),
    ]
