# Generated by Django 4.2.2 on 2023-06-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0003_rename_author_post__author"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                default="draft",
                max_length=20,
            ),
        ),
    ]
