# Generated by Django 4.2.2 on 2023-06-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0004_post_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
